### PR TITLE
Customization to Bootstack charm template

### PR DESCRIPTION
**Pull request by mkalcok**
Few changes to the files created by Bootstack charm template.

These changes were necessary mainly due to inclusion of external ops libraries (`operator_libs_linux`) and implementation of our own library `software_inventory`.

### CODE REVIEW

**Review by gabrielcocenza — DISMISSED** [review]
LGTM. Just need to pass the Lint from the CI

**Review by jneo8 — DISMISSED** [review]

**Review by esunar — DISMISSED** [review]

**Review by jneo8 — CHANGES_REQUESTED** [review]
LGTM. Only need to fix on linter.

**Review by gabrielcocenza — DISMISSED** [review]
LGTM

> LGTM. Only need to fix on linter.

@jneo8 as Martin said before:

> Lint won't pass as there's no code to lint in this PR it's just a preparation.

**Review by rgildein — APPROVED** [review]

**Review by gabrielcocenza — APPROVED** [review]
LGTM

**Pull request merged**
