### PR TITLE
Charm implementation

### PR DESCRIPTION
**Pull request by mkalcok**
Implementation of `software-inventory-exporter` charm including `software-inventory` library. This PR does not contain external libraries so it can be reviewed whole.

### CODE REVIEW

**Review by gabrielcocenza — CHANGES_REQUESTED** [review]
Just some comments and probably some small changes.

**Review by jneo8 — DISMISSED** [review]
Only one not blocking idea.

The pattern here seems can be a independent Mixin class for charm, which has functions like `install_snap`, `config_service`, `update_config`...etc.

Consider we may also implement this kind of exporter somewhere. That will be really useful to reuse it if we put this Mixin in charm lib.

**Review by esunar — DISMISSED** [review]

**Review by chanchiwai-ray — DISMISSED** [review]
LGTM, added a non-blocking comment

**Review by sudeephb — DISMISSED** [review]
LGTM

**Review by gabrielcocenza — DISMISSED** [review]
LGTM +1

**Review by esunar — APPROVED** [review]

**Review by gabrielcocenza — APPROVED** [review]
LGTM

**Pull request merged**
